# Grafana vars
grafana_db_name: grafana
grafana_db_user: grafana
grafana_db_password: SuperSecrete
grafana_admin_password: admin

grafana_ini:
  users:
    allow_sign_up: false
    allow_org_create: false
    auto_assign_org: true
    auto_assign_org_role: Viewer
    default_theme: dark
  security:
    admin_user: admin
    admin_password: "{{ grafana_admin_password }}"
  server:
    http_addr: "{{ ansible_host }}"
    root_url: https://{{ external_lb_vip_address }}:{{ grafana_ini_default.server.http_port }}/

grafana_plugins:
  - grafana-piechart-panel
