collections:
  - name: vexxhost.kubernetes
    source: https://github.com/vexxhost/ansible-collection-kubernetes
    type: git
    version: 896d67092706d01b6fb9d7f4856750819f8898cf
  - name: osa_ops.mcapi_vexxhost
    type: git
    version: master
    source: https://opendev.org/openstack/openstack-ansible-ops#/mcapi_vexxhost
